# --- 2. The Core Engine ---
class LoveOSKernel:
    def __init__(self, cfg=PhysicsConfig()):
        self.cfg = cfg
        self.t = 0
        self.A_accumulated = 0.0  # Karmic Accumulation (Integrated Area)
        self.m = 0.0              # Order Parameter (0=Sleep, 1=Awake)
        
    def step(self, x_t, y_t):
        """
        Simulate one time-step of life.
        x_t: Action/Effort (Real Axis)
        y_t: Intent/Love (Imaginary Axis)
        """
        # [Physics] Generate Micro-Area (a_t)
        # Meaning is generated by Intent (y) and amplified by Action (x)
        a_t = (self.cfg.alpha * np.abs(y_t) + self.cfg.beta * np.abs(x_t * y_t)) * self.cfg.dt
        
        # [Integration] Pile up the history
        self.A_accumulated += a_t
        
        # [Phase Transition] Check for Catastrophe/Awakening
        # If the accumulated area exceeds the Critical Point, the Order Parameter 'm' jumps.
        if self.A_accumulated > self.cfg.critical_area:
            target_m = 1.0
            # Logistic-like smooth transition (Reality doesn't break instantly, it slips)
            self.m += self.cfg.transition_speed * (target_m - self.m)
        else:
            self.m = 0.0
            
        # [Economics] Dynamic Exchange Rate (Kappa)
        # The world rewards you differently based on your state 'm'.
        current_kappa = self.cfg.base_kappa + (self.cfg.awakened_kappa - self.cfg.base_kappa) * self.m
        
        # [Manifestation] Flow = Rate * Area
        dM_t = current_kappa * a_t
        
        self.t += 1
        return a_t, self.A_accumulated, self.m, current_kappa, dM_t
